// Generated by Wrangler by running `wrangler types`
// Runtime types are supplied by @cloudflare/workers-types in tsconfig.
interface __BaseEnv_Env {
  SESSION: KVNamespace;
  ASSETS: Fetcher;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}

declare module 'cloudflare:workers' {
  export const env: Cloudflare.Env;
}
